name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Base Enviorment
      run:  wget -O - https://ppa.bitanical.com/pward8@gatech.edu.gpg.key|apt-key add - &&  echo "deb https://ppa.bitanical.com/apt/debian bionic main" >> /etc/apt/sources.list.d/ppa.bitanical.list
    - name: install Dependecies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libgmp-dev gcc-multilib valgrind portmap rpcbind  libcurl4-openssl-dev bzip2 imagemagick libmagickcore-dev libssl-dev llvm net-tools libtool pkg-config grpc-cs6200 protobuf-cs6200
    - name: Mkake Proto Directory
      run: make protos && make part1 && make part2
